version: "3.5"

services:
  tokenservice:
    image: tokenservice
    build: 
      context: ./TokenService
    ports: 
      - 5000:80
    secrets:
      - jwt-config

  securedwebapi:
    image: securedwebapi
    build:
      context: ./SecuredWebApi
    ports:
      - 5001:80
    secrets:
      - jwt-config

secrets:
  jwt-config:
    file: ./jwt-config.json